#define GAMEOBJECT_EDITOR(Class) GAMEOBJECT(Class)
#define GAMEOBJECT_EDITOR_ABSTRACT(Class) GAMEOBJECT_ABSTRACT(Class)
#define GAMEOBJECT_EDITOR_WITHOUT_CLASS_ID(Class) \
    GAMEOBJECT_WITHOUT_CLASS_ID(Class)
#define GAMEOBJECT_EDITOR_ABSTRACT_WITHOUT_CLASS_ID(Class) \
    GAMEOBJECT_ABSTRACT_WITHOUT_CLASS_ID(Class)
