#ifndef EDITORCOMPONENTSCLASSIDS_H
#define EDITORCOMPONENTSCLASSIDS_H

#include "Bang/ComponentClassIds.h"

#include "BangEditor/BangEditor.h"


NAMESPACE_BANG_BEGIN

SET_COMPONENT_IDS(UIContextMenu,         10000, 10001);
SET_COMPONENT_IDS(HideInHierarchy,       10002, 10003);
SET_COMPONENT_IDS(NotSelectableInEditor, 10004, 10005);

NAMESPACE_BANG_END

#endif // EDITORCOMPONENTSCLASSIDS_H
